on:
  push:
    branches: ["master"]

env:
  IMAGE_NAME: reactjs-image-gcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.io \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG

      - name: Logout
        if: always()
        run: docker logout

  # deploy-service:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   environment: GCP
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Use with SHA
  #       run: |
  #         echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
  #     - name: Deploy via SSH to GCP VM
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.GCP_IP }}
  #         username: ${{ secrets.GCP_USER }}
  #         key: ${{ secrets.GCP_PRIVATE_KEY }}
  #         envs: TAG
  #         script: |
  #           echo "Current location is $(pwd) "

  #           echo "remove the container "
  #           docker stop my-app || true
  #           docker rm my-app || true

  #           echo "Pulling the updating image "
  #           docker pull "69966/${{env.IMAGE_NAME }}:${{ env.TAG }}"

  #           echo "Running new containers "
  #           docker run -d \
  #             --name my-app \
  #             -p 3000:80 \
  #             "69966/${{env.IMAGE_NAME }}:${{ env.TAG }}"
